Add typing and type annotations for icbc
lululxvi/deepxde pull request #1453
Opened 2023-08-21 23:48 UTC by supercgor

creating an extra file called `types.py`, referred from torch.

2023-08-22 22:57 UTC, Saransh-cpp requested changes
Some suggestions 🙂 

Given that DeepXDE supports only Python 3.8+, we can use -
```py
from __future__ import annotations
```
to stay up to date!

I have made a few suggestions regarding the comment above - the rest of the types can be revamped accordingly too!

Also, [`mypy`](https://mypy.readthedocs.io/en/stable/) should be added in the [CI](https://github.com/lululxvi/deepxde/blob/master/.github/workflows/build.yml) to make sure that the types are correct and are being respected throughout the codebase. You can add mypy's configuration in [`pyproject.toml`](https://github.com/lululxvi/deepxde/blob/master/pyproject.toml). This can maybe go in another PR.

(PS: these are just suggestions, the final call would be of DeepXDE's maintainers.)

2023-08-22 22:57 UTC, Saransh-cpp commented on deepxde/icbc/boundary_conditions.py
> +from typing import Any, Callable, List, Optional, overload, Tuple, Union
Given that `DeepXDE` supports Python 3.8+, you should use -
```py
from __future__ import annotations
from typing import Any, Callable, Optional, overload
```

2023-08-22 22:57 UTC, Saransh-cpp commented on deepxde/icbc/boundary_conditions.py
> +        aux_var: Union[NDArray[np.float_], None] = None,
This should work once the suggestion above is applied.
```suggestion
        aux_var: NDArray[np.float_] | None = None,
```

2023-08-22 22:57 UTC, Saransh-cpp commented on deepxde/icbc/boundary_conditions.py
> +        component: Union[List[int], int] = 0,
```suggestion
        component: list[int] | int = 0,
```

2023-08-22 22:57 UTC, Saransh-cpp commented on deepxde/types.py
> +TensorOrTensors = Union[Tensor, Sequence[Tensor]]
```suggestion
TensorOrTensors = Tensor | Sequence[Tensor]

```

2023-08-22 22:57 UTC, Saransh-cpp commented on deepxde/types.py
> +from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union, TypeVar
```suggestion
from __future__ import annotations
from typing import Sequence, TypeVar
```

2023-08-23 01:46 UTC, supercgor commented on deepxde/types.py
> +from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union, TypeVar
Thank you for your suggestions, I will change them later 👍

2025-04-07 03:00 UTC, lululxvi commented
@supercgor @Saransh-cpp Any idea about this PR?

2025-04-07 09:50 UTC, Saransh-cpp requested changes
@lululxvi this looks almost ready, but needs to be polished for merging. It would be great if @supercgor can pick this up again :)

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/backend/backend.py
> +from numpy.typing import NDArray, ArrayLike
These imports (the heavy ones) should be under an [`if typing.TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING).

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/backend/backend.py
> +def is_tensor(obj: object) -> bool:
Using `object` in type hints is not useful + not a very common practice. You would want to narrow this down ideally (because it is as helpful as not having a type hint at the moment).

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/geometry/geometry.py
> +from numpy.typing import NDArray
Should be moved in an `if` condition.

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/geometry/geometry_2d.py
> +from numpy.typing import ArrayLike, NDArray
Ditto

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/geometry/geometry_2d.py
> +from ..types import Tensor
Ditto

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/geometry/geometry_2d.py
> +        # diff_x1_x2 = diff_x1_x3 = diff_x2_x3 = 0.0
There are a couple of code (logic) changes in this PR, which should not be the case.

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/geometry/timedomain.py
> +class GeometryXTime():
```suggestion
class GeometryXTime:
```

2025-04-07 09:50 UTC, Saransh-cpp commented on deepxde/types.py
We should not call this file as `types` as [types is a builtin Python module](https://docs.python.org/3/library/types.html#module-types).

2025-04-07 09:50 UTC, Saransh-cpp commented on pyproject.toml
> +ignore_missing_imports = true
```suggestion
ignore_missing_imports = true

```

2026-03-13 16:49 UTC, echen5503 commented
@hheei any updates here?

2026-07-06 17:51 UTC, closed without merging